appoptics/appoptics-apm-node

- CONTRIBUTING.md
- README.md
- lib/event.js
- lib/index.js
- lib/probes/generic-pool.js
- test/probes/co-render.test.js
- test/probes/generic-pool.test.js
- test/probes/hapi.test.js
- test/versions.js
Patch fixes and testing updates for pending v5.5.0 release
> V5.5.0 cleanup

- lib/probes/koa-router.js
- lib/probes/koa.js
- package.json
- test/probes/koa.js
- test/versions.js
- add support for koa-router v6 & v7
- update tests
- use logMissing() for patching errors
> koa, koa-router v7 support [AO-10903, AO-11459]

- .eslintrc.yaml
- guides/api.md
- guides/configuration.md
- lib/addon-sim.js
- lib/api.js
- lib/index.js
- lib/log-formatters.js
- lib/probes/pino.js
- lib/probes/winston.js
- lib/require-patch.js
- lib/span.js
- package-lock.json
- package.json
- test/custom.test.js
- test/event.test.js
- test/logging.test.js
- test/probes/pino.test.js
- test/probes/winston.test.js
- test/probes/winston/test-emitter.js
- test/versions.js
- insert trace IDs into logs
- automatic for pino, winston (dunyan tbd)
- manual support for all using new function
- custom metrics via `ao.sendMetric()`
- fix config file path error
- provide additional functions/properties for disabled mode
- update docs
> 6.1.0 [AO-8305, AO-12329, AO-12470]

- CHANGELOG.md
- lib/c-lib-env-vars.js
- lib/index.js
- lib/probes/@hapi/hapi.js
- lib/probes/@hapi/vision.js
- lib/probes/amqplib.js
- lib/probes/amqplib/callback_api.js
- lib/require-patch.js
- package-lock.json
- package.json
- test/probes/@hapi-hapi.test.js
- test/probes/@hapi-vision.test.js
- test/probes/hapi.test.js
- test/probes/hapi/hapi-17-and-above.js
- test/probes/morgan.test.js
- test/probes/vision.test.js
- test/probes/vision/vision-5-and-above.js
- test/versions.js
v6.5.0
- fix for node v11.10.0+ corrupted histograms
- support new @hapi/hapi and @hapi/vision packages
- improved environment variable handling
> 6.5.0 [AO-12471, AO-12764, AO-12791, AO-13167]

- package.json
- avoid warnings about license due to form
> package.json - change license form [AO-14757]

- lib/require-patch.js
- don't look for package.json for builtin packages
> lib - optimize builtin patching [AO-14756]

- lib/probes/zlib.js
- test/probes/zlib.test.js
- add Brotli support
- fix "event already sent error in zlib test"
- test Brotli compression
> zlib - fixes [AO-11896, AO-11898]

- lib/probes/zlib.js
- test/probes/zlib.test.js
- add Brotli support
- fix "event already sent error in zlib test"
- test Brotli compression
> zlib - support Brotli

- package-lock.json
- package.json
- update tedious to 6.6.2
- add jiri to contributors
> Bookkeeping

- README.md
- guides/contributing.md
- mention dev edition
- remove dev stuff from readme
- create contributing.md for dev information
- simplify language
- move to shorter lines
- add certificate of origin to contribution guide
> update the readme

- test/probes/morgan.test.js
- fix intermittent failures in morgan testing
> test/probes/morgan - fix regex

- lib/notifications-listener.js
merge after 117 and 118. only 1 file will differ at that point.
> Extra special message fix

- guides/configuration.md
- lib/probes/cassandra-driver.js
- lib/probes/express.js
- package.json
- add support for cassandra-driver >= v4.4.0
- document proxy in configuration guide.
> Cassandra fixes

- package.json
- test.sh
sync up so install from github works
> New bindings

- lib/probes/koa.js
- lib/require-patch.js
- pass constructor options for koa
- minimize builtin lookups when patching
> koa fix and patch optimization

- CONTRIBUTING.md
- guides/api.md
- guides/configuration.md
- lib/api.js
- package.json
* mention suppressing agent messages via APPOPTICS_LOG_SETTINGS from v10.0.0 release
* mention custom metrics are aggregated for AO-18250
> Docs updates

- package.json
* bumped version to 10.0.1
* #140 
* #139
> Release version 10.0.1

- dev/repo/reset.sh
This pull request adds guard conditional around force push into dev repo.
Note that main repo also has branch protection on master.
> Dev setup hardening

- README.md
- guides/lambda-configuration.md
This pull request updates support email address in documentation.
> AO-20164-Update-Support-Email-Address

- README.md
- docs/github-actions.md
- docs/release-process.md
This Pull Request updated the README document and adds initial versions of docs for Release Process and GitHub Actions.
The two commits are result of rebasing multiple online editing commits. Branch stays open for further iterations. Feel free to participate.
> AO-20351-Update-Documentation

- .github/workflows/document.yml
- docs/supported-components.human
- package-lock.json
- package.json
- test/logging.test.js
This pull request handles minor existing issues with the Document workflow (`testeachversion`) to allow documentation publishing.
>  AO-20494-Finalize-Document-Workflow-1

- package-lock.json
- package.json
This is a pull request is for a prerelease version bump.
Merging this pull request does not trigger the release.
The trigger is by git tag push that will come after all workflows pass.
> 10.1.1-prerelease.0

- docs/github-actions.md
This Pull Request:
- Addresses TODO items in GitHub actions documentation.
Branch stays open for further iterations. Feel free to participate.
> AO-20351-Update-Documentation-no-action

- lib/api.js
This Pull Request removes conditionals that use internal environment variables are in API code.
Pull Request merges into nh-main.
> NH-5407-Remove-AO_DEBUG_-Conditionals-from-Code

- lib/probes/generic-pool.js
This pull request removes a confusing comment that was not removed in previous merge due to confusing comments :).
This whole thing is very confusing!
> NH-5268-Remove-semver-Conditionals-for-Outdated-Node-Versions

- dev/docker-compose.yml
- package-lock.json
- package.json
This is a pull request is for a prerelease version bump.
It depends on newly (pre)released bindings.
Merging this pull request does not trigger the release.
The trigger is by git tag push that will come after all workflows pass.
> 10.1.1-prerelease.1

- CONFIGURATION.md
- docs/api.md
- lib/api-sim.js
- lib/api.js
- lib/probes/morgan.js
- test/no-addon/custom.test.js
- test/probes/bunyan.test.js
- test/probes/morgan.test.js
- test/probes/pino.test.js
- test/probes/winston.test.js
This pull request modifies trace context in logs to match the [Open Telemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md#plain-text-formats).
1. Modified API used for logging:
- Removed `getFormattedTraceId` method ([added in v6.1](https://github.com/appoptics/appoptics-apm-node/blob/master/CHANGELOG.md#v610)).
- Modified `insertTraceIdsIntoLogs` to generate an object with top key of `sw` rather than `ao`
- Modified `insertTraceIdsIntoLogs` to generate an object with three fields: `trace_id`, `span_id`, `trace_flags`.
2. Updated `morgan` probe to use updated API.
- Replaced `getFormattedTraceId` with `insertTraceIdsIntoLogs`.
- Removed a "flaky conditional" that under certain conditions would have omitted the …
> NH-4534-Trace-Context-in-Logs

- dev/Dockerfile
- package-lock.json
- package.json
This is a pull request is for a prerelease version bump.
It depends on newly (pre)released bindings.
Merging this pull request does not trigger the release.
The trigger is by git tag push that will come after all workflows pass.
> 10.2.2-prerelease.0

- package-lock.json
- package.json
This is a pull request is for a prerelease version bump.
It depends on newly (pre)released bindings.
Merging this pull request does not trigger the release.
The trigger is by git tag push that will come after all workflows pass.
> 10.2.2-prerelease.1

- CONFIGURATION.md
- docs/probe-defaults.md
This pull adds a basic probe defaults document and links it from the configuration doc.
> NH-12822-Document-Probe-Configuration-Options

- lib/debug-custom.js
This pull request closes #282
- Pull Request merges into `nh-main`. `master` branch uses package from NPM.
> NH-5414-Update-Dependencies-devDependencies-6 (debug-custom) (fix)
