install-appoptics-bindings.js
lib/probes/fs.js
test/probes/fs.test.js

lchown, lchownSync, lchmod, and lchmondSync have been deprecated since 0.4.7. They have been replaced with chown, chownSync, chmod, and chmodSync. It turns out that it is not implemented on linux at all (https://github.com/nodejs/node/issues/19868) but somehow seems to have been missed by the testing. Updating gulp and/or gulp-mocha caused the tests for those functions to fail.

fs remove deprecated since 0.4.7 functions

---

lib/span.js
lib/utility.js

Move the toError function from utility.js to static Span method in span.js.
Span is the only user of this function and it converts string as well as passes Errors.

Move toError from Utility to Span.

---

deps.sh
package.json

- change postinstall script from appoptics-bindings to install dependencies
- put production check in `deps.sh` (they are dev dependencies).
- move dev-dependencies from`optionalDependencies` to `deps.sh`
- update `testeachversion` to 6.0.0

Package cleanup

---

lib/index.js
package.json
test/probes/fs.test.js

In order to support async/await it is necessary to move to `async-hooks`. `cls-hooked` uses `async_hooks`, which enables handling async/await. It falls back to `AsyncWrap` for versions of node prior to 8. `AsyncWrap` is unsupported but so is `async-listener`, what `continuation-local-storage` uses now.h
I have run the test matrix using `cls-hooked` and the results are identical to those obtained using `continuation-local-storage`. I have modified the `generic-pool` probe/patching and testing to test their new version 3, promise-based API. It passes the test when using `cls-hooked` but fails when using `continuation-local-storage` (even for node version 6, so `AsyncWrap` handles some things that `async-listener` doesn't.
The only real alternative to this is to implement a combination of …

use cls-hooked, retire continuation-local-storage

---

.eslintrc.yaml
lib/probes/generic-pool.js
test/probes/generic-pool.test.js

Change patching for promise-based version 3 of generic-pool.
Create real test for generic pool that detects incorrect context through promises.
Add single async/await test for node version 8 and above.

Generic pool fixes

---

lib/probes/zlib.js

Remove incorrect call to bindEmitter().
Make indexOf test easier to read.

Fix bindEmitter bug.

---

lib/index.js
lib/probes/express.js
lib/probes/http.js
lib/probes/koa.js
lib/probes/mongodb-core.js
lib/probes/pg.js
lib/probes/redis.js
lib/probes/zlib.js
lib/require-patch.js
package.json
test/basics.test.js
test/error.test.js
test/event.test.js
test/helper.js
test/probes/crypto.test.js
test/probes/express.test.js
test/probes/fs.test.js
test/probes/koa.js
test/probes/koa.test.js
test/probes/redis.test.js
test/probes/redis/pubsub.js
test/span.test.js

- Fixes possible file corruption by http instrumentation [AO-9715, AO-9739]
- Add support for koa@2 [AO-9864]
- Use cls-hooked for node versions 8+
- Maintain context for redis pub/sub.
- Logging improvements.
- Testing improvements.
- Use appoptics-bindings@5.4.1 for host metadata changes

v5.5.0 [AO-9660, AO-9715, AO-9739, AO-9864]

---

lib/index.js
lib/span.js
test/custom.test.js
test/helper.js

- Change "no span name or builder" from debug to warn.
- Distinguish between set and get errors for last span.
- custom.test.js now tests for expected logging.

Custom test cleanup

---

lib/event.js
lib/probes/http.js
test/event.test.js
test/helper.js

Via code-inspection it appears that a bad port can happen when the `req.headers.host` is present but does not contain a `:port` component. This PR fixes that by using the default if `:port` is missing.
In the case above the value is being set to NaN which, all logic to the contrary, is considered a number by JavaScript. I also added checks to assure that a KV value is not being set to NaN. That does imply that if someone really wants to set that value they will need to make it a string value. Tests to assure that NaN is not allowed are included.

Possible bad port fix [AO-10015]

---

lib/index.js
lib/probes/fs.js

- cleans service per https://swicloud.atlassian.net/browse/AO-10242
- sidesteps oboe validation by deleting/restoring APPOPTICS_SERVICE_KEY env var, if present
- eliminates ambiguous oboe logs (overriding default using env var)
- tested using old version of oboe that doesn't transform bad service names.
- oboe log 'client id' value verifies transformed name without override log message.
- fixes undefined FilePath error [AO-10347]

Cleanse service name [AO-10253, AO-10347]

---

lib/probes/fs.js

propagate .native functions to patched functions
for realpath and realpathSync.
this change prevents the esm package from core dumping.

fix for esm needing .native functions [AO-10300]

---

lib/probes/amqplib.js
lib/probes/cassandra-driver.js

Minor corrections
- amqplib was defaulting the `SourceTrace` message header twice.
- cassandra-driver is patching logs to patching and uses `()` for functions that are missing.

Probe improvements

---

test/probes/mongodb-core.test.js

When running multiple matrix tests in parallel the mongo tests would cause others to fail because they all used the same database and collection names.
mongodb-core is the last of the database tests to use unique names. All the tests to depend on the environment variable `AO_IX` to be set - that is used to construct the unique names. Running locally there is no need to set `AO_IX` because only one test runs at a time. These commits just add some debugging output that allows makes it easier to see what is happening.

Fix mongodb-core tests to use unique DB names [AO-8024]

---

lib/index.js
lib/probes/mongodb-core.js
test/custom.test.js
test/probes/mongodb.test.js
test/probes/mongoose.test.js

- handle old `Group_Reduce` KV source in addition to new.
- add `aggregate` `QueryOp` (stop synthesizing `count`)
- handle class and object versions of `bindings.Reporter` (allowed testing with N-API bindings)
- minor binding error message changes

Mongo updates

---

env.sh
lib/index.js
lib/loggers.js
lib/probes/express.js
package.json
test/basics.test.js
test/probes/express.test.js

- log bind errors to the the 'bind' logging level, not warn, debug.
- log not-tracing bind emitter to 'info'
- remove always and never references

Fix express tests for better named route spans

---

guides/configuration.md

* moved descriptions of `traceMode` and `transactionSettings` into main config file section
* updated the `traceMode` description to hopefully make clear that while the agent does not set a default, the expected default behaviour (dictated by remote settings) is `enabled`, so customers shouldn't have to set it explicitly.

Config guide updates

---

lib/api.js
test/docker/mac-os-test-env/dc.sh
test/docker/main.yml

- use ao object, not exports
- loosen emitter check
The loosen emitter check is because web sockets end up with scenarios in which there are not headers in the object. It's a fair question whether bindEmitter() should accept any emitter-like object, i.e., one with an `on` method. At this time the only use is for http client/server and this is sufficient. Maybe have specific calls for `bindHttpReq`, `bindHttpRes`, `bindXyzzy` when other objects need to be supported.

lib/api.js - minor fixes

---

lib/probes/http.js
package-lock.json
package.json

- use emitter.prependListener()
- replaces event-pre-handler.js/patchEmitter()
I'm going to base trigger trace work on this branch because they both fiddle primarily with lib/probes/http.js.

use native function for prepending listeners [AO-12085]

---

lib/api.js
lib/probes/@hapi/hapi.js
lib/probes/zlib.js
test/probes/hapi/hapi-16-and-below.js
test/probes/hapi/hapi-17-and-above.js
test/probes/vision/vision-4-and-below.js
test/probes/vision/vision-5-and-above.js

AO-14149
- update `guides/configuration.md`.
- bind context for response finalizer in `instrumentHttp`.
- `lib/probes/@hapi/hapi.js` - consistently report template language without dot.
- `lib/probes/zlib.js` - only bind emitter when context exists.
- `test/` various - use port 3500 to avoid conflicts with commonly used 3000.
- `test/probes/hapi/hapi-17-and-above.js` - add `zlib` testing and fix when invalid `vision` plugin.

6.7.1 candidate

---

lib/event.js

output only one log entry for bad KV data type errors [AO-14453]
[AO-14453]: https://swicloud.atlassian.net/browse/AO-14453

lib/event - improve bad KV pair logging

---

lib/probes/http.js

- supply a default when there is no TransactionName. [AO-14454]
- prepare for a numeric code return on errors [AO-14437]
- debounce the error logging.
The second item requires an appropriate release of appoptics-bindings.
[AO-14454]: https://swicloud.atlassian.net/browse/AO-14454
[AO-14437]: https://swicloud.atlassian.net/browse/AO-14437

lib/probe/http - prevent undefined TransactionName

---

lib/span.js

- aob.reporter.sendNonHttpSpan() can now return a numeric code
- log an error (debounced) if it occurs.

lib/span.js - handle error code return [AO-14337]

---

lib/loggers.js
test/logging.test.js

- when a log entry is generated reset both the count and time-window start.
- fix tests that previously were broken because of the previous item.

loggers - reset both count and time on logging [AO-14438]

---

lib/probes/mongodb-core.js
test/probes/mongodb-core.test.js

- don't instrument node > 10 if version < 3.0.0 [AO-14456]
- explain 'db.collection' syntax in commands (in test/probes/mongodb-core.test.js)
[AO-14456]: https://swicloud.atlassian.net/browse/AO-14456

lib/probes/mongodb-core - node version check

---

CONTRIBUTING.md
lib/probe-defaults.js
lib/probes/mongodb-core.js
lib/probes/mongodb.js
package-lock.json
package.json
prepack.js
test/probes/mongodb-core.test.js
test/probes/mongodb.test.js
test/versions.js

- add support for mongodb v3.3.0+ which no longer uses mongodb-core.
- add tests for mongodb v3.0.0+ with new command api.
- add to versions.js for matrix testing.
- updates to mongodb/mongodb-core tests to verify RemoteHost (was silently failing).

mongodb probe [AO-14417]

---

appoptics-apm.json
guides/configuration.md
lib/get-unified-config.js
lib/probes/fs.js
lib/span.js
test/probes/fs.test.js
test/unified-config.test.js

- allow "ignoreErrors" property in the "fs" config.
- provide checking to verify ignoreErrors will allow the `in` operator to be used.
- implement general ignore error logic in `lib/span`
- use span logic in fs probe.
- fixes unreported bug where FileDescriptor would not be added to span exit event.

allow the fs probe to ignore specific errors [AO-12757]

---

lib/probes/@hapi/hapi.js
lib/probes/@hapi/vision.js
lib/probes/http.js
lib/probes/https.js
lib/probes/mongodb-core.js
lib/probes/mongodb.js
lib/require-patch.js
test/probes/mongodb-core.test.js
test/probes/mongodb.test.js
test/versions.js

- move version fetching to require-patch.js and pass version to probes
- align mongodb and mongodb-core probes and test code more closely
- remove sampleTrace() references in mongodb/mongodb-core testing
- backtrack on test-skipping logic because it fails to execute afterEach()

mongodb probe fixes [AO-14417]

---

lib/index.js

lib - use llhttp version if present [AO-14657]

---

lib/get-unified-config.js
test/unified-config.test.js

Configuration parser was populating fields that were never used and filtering logic was expecting fields that were never populated.

Populate proper values in transaction settings

---

test/custom.test.js

Add tests for `q` and `bluebird` to verify that context is maintained when using the custom instrumentation API.

test promise libraries with custom API

---

lib/probes/tedious.js
test/probes/tedious.test.js

- lib/probes/tedious - don't add KV if no database
- test/probes/tedious - test no database case

tedious - handle no database specified

---

CHANGELOG.md
CONTRIBUTING.md
README.md
guides/api.md
guides/configuration.md
lib/addon-sim.js
lib/api-sim.js
lib/api.js
lib/get-unified-config.js
lib/index.js
lib/metrics.js
package.json
test/probes/bcrypt.test.js
test/probes/pg6-plus.js
test/unified-config.test.js
test/versions.js

N.B. requires bindings v9 (implements `Reporter.sendMetrics()`) to be released before this.
This release implements [AO-10912] and minor test updates.
- implement `sendMetrics()` which calls `Reporter.sendMetrics()`.
- rewrite `sendMetric()` as a wrapper around `sendMetrics()` so non-breaking
- add `sendMetrics()` to guides/api.md
- deprecate `sendMetric()` in guides/api.md
- config file `runtimeMetrics` or env var `APPOPTICS_RUNTIME_METRICS`
[AO-10912]: https://swicloud.atlassian.net/browse/AO-10912

VM metrics

---

lib/addon-sim.js
lib/api-sim.js
lib/api.js
lib/event.js
lib/log-formatters.js
lib/probes/@hapi/hapi.js
lib/probes/@hapi/vision.js
lib/probes/cassandra-driver.js
lib/probes/co-render.js
lib/probes/http.js
lib/probes/koa-resource-router.js
lib/probes/koa-route.js
lib/probes/koa-router.js
lib/probes/koa.js
lib/probes/memcached.js
lib/probes/morgan.js
lib/probes/node-cassandra-cql.js
lib/probes/zlib.js
lib/span.js
package.json
test.sh
test/basics.test.js
test/custom.test.js
test/helper.js
test/logging.test.js
test/no-addon/custom.test.js
test/probes/http-common.js
test/probes/http-trigger-trace.test.js
test/probes/morgan.test.js
test/span.test.js

- Event.last => ao.lastEvent
- Span.last => ao.lastSpan
the base of this branch is `p9p-noti+minimal`; to minimize conflicts this should be reviewed and merged only *after* PR 117 has been merged. there will be 20 files changed after that. other than the deprecation code itself, all the changes are to replace `last = Event.last` and `{last} = Event` with `last = ao.lastEvent`, and analogous changes for `Span.last`

deprecate Event.last and Span.last

---

lib/probes/bunyan.js
lib/probes/generic-pool.js
lib/probes/koa-route.js
lib/probes/koa-router.js
lib/probes/mongoose.js
lib/probes/mysql.js
lib/probes/node-cassandra-cql.js
lib/probes/pg.js
lib/probes/pino.js
lib/probes/raw-body.js
lib/probes/winston.js

require-patch fetches the version; remove version fetches from probes.
- bunyan
- generic-pool
- koa-route
- koa-router
- mongoose
- mysql
- cassandra-driver
- pg
- pino
- raw-body
- winston

lib/probes: use info.version

---

appoptics-apm.json
lib/probe-defaults.js
lib/probes/http.js
package.json
test/probes/http-common.js

- http server behind nginx ClientIP is missing/not useful
- add configuration option to specify remote address header
- set ClientIP to '' when ClientIP is undefined so Event.set() doesn't log error.

8.1.0 ClientIP fix

---

CHANGELOG.md
LICENSE
guides/api.md
guides/lambda-configuration.md
guides/migrating.md
lib/api.js
lib/event.js
lib/index.js
lib/span.js
package.json
test.sh
test/composite/axios.test.js
test/context-no-mocha.test.js
test/custom.test.js
test/helper.js
test/lambda/get-lambda-version.js
test/lambda/local-tests.js
test/lambda/local.test.js
test/lambda/remote.test.js
test/span.test.js

the bulk of the non-test changes are to use a native promise interface to execute lambda functions. previously `pStartOrContinueTrace` was a simple wrapper that wrapped the user's promise-returning function and then called `startOrContinueTrace` which used the existing callback mechanism to signal completion. that arrangement didn't allow the result of the promise to be evaluated before exiting the span, and that is required in the lambda environment in order to detect non-error returns that the agent should treat as errors. `pStartOrContinueTrace` now parallels `startOrContinueTrace` with a few optimizations. a related change is a new `Span.runPromise()` instance function.
the agent now captures whether an inbound-x-trace was received; lambda functions do not attempt to return an x-trace …

additional lambda changes

---

lib/api.js
lib/probes/http.js
lib/span.js
package.json
test/lambda/local.test.js

- flag non-api-gateway/rest lambda invocations as lambda
- report token bucket KVs as strings
- fix unrelated-to-lambda transaction name bug

Lambda fixes

---

lib/probes/fs.js
test/probes/fs.test.js

Of the synchronous path-based fs operations, only `openSync` checked for ignored operations.
My thinking was to not introduce even slight additional overhead for the synchronous functions unless it addressed the specific customer problem. while the asynchronous functions needed the finalize function in order to capture the created span, the synchronous functions didn't, so avoiding the finalize function slightly reduced the overhead. in retrospect the slight reduction was not worth 1) different behavior for async and sync operations or 2) avoiding the slight increase in overhead for synchronous operations.
this pr makes path-based operations work the same for async and sync versions - errors from any operation can be ignored. this addresses issue #65 (reopened) and [AO-18483].
[AO-18483]: …

extend ignore errors to all fs path-based operations

---

lib/api-sim.js
lib/api.js

@bdehamer ran into the following error with our agent version 10.0.0 on Node 14.15
```
(node:1) Warning: Accessing non-existent property 'lambda' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
at Object.get (internal/modules/cjs/loader.js:664:5)
at module.exports (/app/node_modules/appoptics-apm/lib/api.js:37:10)
at Object.<anonymous> (/app/node_modules/appoptics-apm/lib/index.js:372:53)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at Module._preloadModules …
```

AO-18716 fix node 14 non-existent property warning

---

lib/get-unified-config.js
test/get-unified-config.test.js

set defaults in one place, at the start.
add tests, including a test key which can be replaced with a real one when ready. the test key must have eeid 'lambda' and a default value.

handle defaults in one place, correctly

---

.github/docker-node/node-agent-runner.Dockerfile
.github/workflows/docker-node.yml
dev/repo/reset.sh

This Pull Request is the **1st** in a series of Pull Requests to set up GitHub Actions.
The first commit (2bab9f3) added the `docker-node` directory under the `.github` (hidden) directory. It houses a Dockerfile to be used as main container for GitHub Actions (Dockerfile setup similar to dev container, directory name is similar to the upstream repo).
The second commit (3dd106c) added a workflow that builds and publishes an image to GitHub Container Registry (ghcr.io). When run, the workflow creates a single package named [node-agent-runner](https://github.com/appoptics/appoptics-apm-node/pkgs/container/appoptics-apm-node%2Fnode-agent-runner) scoped to `appoptics/appoptics-apm-node` (the repo). The workflow is triggered by a push of a Dockerfile. Hence it has already [ran …

AO-20334-Create-GitHub-Actions-Test-Publish-Workflows-1

---

.github/workflows/accept.yml
.github/workflows/push.yml
.github/workflows/review.yml
test/probes/http-websocket-common.js

This Pull Request is the **2nd** in a series of Pull Requests to set up GitHub Actions.
1. First commit (5ec2565) added **Push** workflow (triggered by a push) that runs core tests on node 14. Node is set on the GitHub Actions runner and tests run on it. Since the workflow is triggered by a push it has already [ran successfully](https://github.com/appoptics/appoptics-apm-node/actions/runs/1144733650) on commits in this Pull Request.
2. Second commit (801298d) added **Review** workflow (triggered by a pull request) that runs full test suite on node 14 inside a container linked to a network of service containers. Since the workflow is triggered by a pull request it has already [ran successfully](https://github.com/appoptics/appoptics-apm-node/actions/runs/1144865750) on this Pull Request. …

AO-20334-Create-GitHub-Actions-Test-Publish-Workflows-2

---

.github/scripts/testeachversion-clean-output.sh
.github/scripts/testeachversion-rename-files.sh
.github/workflows/document.yml

This Pull Request is the **3rd** in a series of Pull Requests to set up GitHub Actions.
Commit (859ab3c) adds a Document workflow triggered manually, supporting scripts in `.github/scripts` and a target directory (`docs`) that is currently empty.
Workflow runs a [`testeachversion`](https://www.npmjs.com/package/testeachversion) per package in a matrix, generates a summary file, creates an automated commit into branch and opens a pull request. End result is a docs directory containing supported-components.human file and supported-components-data directory with summary and raw data for each package.
- The workflow is of the "dip a toe in the water" type. If all works as expected over time, it will replace https://github.com/appoptics/apm-test-node and the corresponding @aws setup.
- …

AO-20334-Create-GitHub-Actions-Test-Publish-Workflows-3

---

.github/workflows/accept.yml
.github/workflows/document.yml
.github/workflows/review.yml
package-lock.json
package.json
test/probes/hapi/hapi-17-and-above.js
test/probes/vision/vision-5-and-above.js

This Pull Request "formally" enables support for Node 16 while maintaining current test and dependency setup.
The first commit (64f2853) upgrades @hapi/hapi to version 20. 
- Since Hapi 18 is not compatible with Node 16 ([though not explicitly stated](https://hapi.dev/resources/status/#hapi)). Tests were set so that the `hapi` tests do not run for node versions at or above 16. 
- Since Hapi 20 is not compatible with Node 10.  Tests were set so that the `@hapi/hapi` tests do not run for node versions at or below 11. 
Second commit (f55d44e) added Node 16 to Accept workflow test matrix.
Third commit (04ef357) includes GitHub Actions workflow improvement (health checks).
Fourth (22afec8) updates package-lock.json
Fifth commit (9c8a4b4) added Node 16 to  Document workflow test matrix.
Manual …

AO-20084-Enable-Support-For-Node-16

---

.github/utils/client.js
.github/utils/package-lock.json
.github/utils/package.json
.github/utils/server.js
.github/workflows/verify.yml

This pull request is the **last** in a series of Pull Requests to set up GitHub Actions (for this repo and the upstream one).
Pull Request adds a Verify (`verify.yml`) workflow that runs after the Release workflow has completed.
It provides confidence that a released package can successfully install and auto instrument apps on a wide variety of node and operatiing system combinations.
Workflow will load the [Target Group from the bindings repo](https://github.com/appoptics/appoptics-bindings-node/blob/master/.github/config/target-group.json) and for each image in group:
- Install  Appoptics agent (either the released version or the one specified manually).
- Check that installation of binary completed successfully (either from prebuilt tarball or from source).
- Start an instrumented http …

AO-20158-Package-Install-Tests

---

.github/workflows/accept.yml
.github/workflows/document.yml
.github/workflows/review.yml
dev/docker-compose.yml
env.sh
test/probes/oracledb.test.js

This pull request replaces the "informal" Oracle database used for testing with an [Oracle Database 18c (18.4.0) Express Edition (XE)](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-oracle-database-18c-express-edition-in-a-container) from a SolarWinds Dockerhub account. Tests and workflows adapted. All pass.

AO-20361-Replace-Oracle-DB-used-for-testing

---

.github/workflows/release.yml

This pull-request changes the git tag used to trigger the Release workflow from `alpha` to `prerelease`.
Moving fwd:
- Version promotion will be done with: `npm version prerelease --preid prerelease`.
- Resulting in `"version": "10.0.2-prerelease.1"` in `package.json`. 
- Will be npm tagged `prerelease`.

AO-20334-Create-GitHub-Actions-Test-Publish-Workflows-5

---

.eslintrc.js
lib/addon-sim.js
lib/api-sim.js
lib/api.js
lib/event.js
lib/get-unified-config.js
lib/index.js
lib/metrics.js
lib/notifications-listener.js
lib/probes/@hapi/hapi.js
lib/probes/director.js
lib/probes/http.js
lib/probes/koa.js
lib/probes/mongodb.js
lib/probes/pg.js
lib/require-patch.js
lib/span.js
prepack.js

This Pull Request is the **7th** in a series of pull requests to update the build setup and manage dependencies in package.json.
Core library files were linted and auto-fixed in PR #164 using new implemented configuration in PR #163. This pull request handles the cases where auto fixing did not change JavaScript code, and an eslint error was emitted.
This linting pass should **not** be considered a code change. 
Manual edits included:
1. Changes to conditionals ([no-mixed-operators](https://eslint.org/docs/rules/no-mixed-operators))
2. Removing unneeded constructors ([no-useless-constructor](https://eslint.org/docs/rules/no-useless-constructor))
3. Modifying how existence of object own properties are evaluated ([no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)) …

AO-20279-Update-NPM-Build-Test-Setup-7

---

.github/workflows/accept.yml
.github/workflows/document.yml
.github/workflows/review.yml
CHANGELOG.md
dev/docker-compose.yml
package-lock.json
package.json
test/probes/tedious.test.js

This Pull Request is the **9th** and hopefully the real last one in a series of pull requests to update the build setup and manage dependencies in package.json in preparation for release.
First commit (0aefb39) updates a service package to address Dependabot concerns.
Second (13a8627) and third (b31c9f0) commits handled issues specific to the `tedious` probe, MSSQL server and Document workflow results. Test now fail when they should and pass when they can. Tedious package support is two versions back from latest (there is a need and ticket for a probe update).
Fourth (3bf1909) and fifth (3276d10) commits handled issues specific to the `restify` probe tests and Document workflow results. 
Last commit updated CHANGELOG.md with missing data from past releases.

AO-20279-Update-NPM-Build-Test-Setup-9

---

.github/workflows/accept.yml
.github/workflows/document.yml
dev/Dockerfile

This pull request adds support or Node 17.
Changes are limited to dev setup and GitHub Actions workflows.
Bindings support was added in: https://github.com/appoptics/appoptics-bindings-node/pull/84
All [acceptance tests pass](https://github.com/appoptics/appoptics-apm-node/actions/runs/1492694206).
Document workflow [ran as expected](https://github.com/appoptics/appoptics-apm-node/actions/runs/1493552952). [Supported components](https://github.com/appoptics/appoptics-apm-node/blob/test-each-version-2021-11-22-23-26-44/docs/supported-components.human) data generated.

AO-20593-Add-Support-for-Node-17

---

.github/utils/server.js

This pull request applies the simplest solution to the "flakiness" problem - allow oboe to try by itself - it increased readyToSample wait five fold to 5000 ms.

AO-20643-Verify-Workflow-flaky-due-to-AppOptics-not-ready-to-sample

---

lib/addon-sim.js
test/error.test.js
test/probes/amqp.skip-test.js
test/probes/fs.test.js
test/probes/http-websocket-common.js
test/probes/koa-router.test.js
test/probes/memcached.test.js
test/probes/oracledb.test.js
test/probes/pg6-minus.js
test/probes/pg6-plus.js
test/probes/redis.test.js
test/probes/zlib.test.js

This pull request removes reference to sampleTrace(), an old function, replaced by getTraceSettings() circa 2019, from tests and addon sim.
All tests pass.

AO-14556-Remove-sampleTrace-From-Tests

---

test/probes/express.test.js
test/probes/hapi/hapi-16-and-below.js
test/probes/hapi/hapi-17-and-above.js
test/probes/http-common.js
test/probes/koa.js
test/probes/raw-body.test.js
test/probes/restify.test.js
test/probes/vision/vision-4-and-below.js
test/probes/vision/vision-5-and-above.js

This pull request replaces `request` with `axios` in tests as `request` is now fully deprecated.
Note that `request` itself is still instrumented and hence there is a `request` test and it is still a "dev dependency".

AO-16676-Replace-request-with-axios

---

CONFIGURATION.md
lib/get-unified-config.js
lib/index.js
test/get-unified-config.test.js

This pull request removes the code used to detect and potentially handle conflicts with `newrelic`, `strong-agent` and `appdynamics` and also removes the `ignoreConfilicts` config setting.
The code, as implemented, checked the require cache to see if one of the ignored packages is loaded. However, since the AppOptics agent is  required, per our instructions, **before** any other packages, the agent will not be able to find anything in the required cache when the code is run.
Since this behavior is foundational, the code only checks edge-cases (AppOptics agent was not required first) of edge cases (other packages that may create conflicts were required prior). For simplification it has been removed.
- Pull Request merges into `nh-main` branch. Agent built from `master` will stay unchanged.

NH-5315-Remove-Handle-Conflicts-Code

---

lib/probes/generic-pool.js
lib/probes/http.js
lib/probes/mongodb-core.js
lib/probes/zlib.js
test/probes/fs.test.js
test/probes/generic-pool.test.js
test/probes/http-common.js
test/probes/restify.test.js
test/probes/zlib.test.js
test/versions.js

This pull request removes node version checks for outdated versions that will not be supported moving fwd.
The following probes are affected:
- generic-pool (972c567)
- zlib (369840e)
- mongodb-core (56a45ed)
- http (03d35d0)
- Pull Request merges into `nh-main`.

NH-5268-Remove-semver-Conditionals-for-Outdated-Node-Versions

---

lib/probes/express.js
lib/probes/koa-route.js
lib/probes/koa-router.js
package.json

This pull request removes `methods` from dependencies.
`methods` was added as dependency in https://github.com/appoptics/appoptics-apm-node/commit/a04fafd78ea8a8d9e8ef1a6672a634c02b6b35e2
Package [does little](https://www.npmjs.com/package/methods) and can be replaced with native `http.METHODS`.
- Pull Request merges into `nh-main`. Agent built from `master` will maintain dependency`.

NH-5414-Update-Dependencies-devDependencies-2

---

lib/probes/express.js
package.json

This pull request removes `array-flatten` from dependencies.
`array-flatten` was added as dependency in https://github.com/appoptics/appoptics-apm-node/commit/9b2a6a058260350ed7091ea12673d0c352f8587c. 
No longer needed. Array.prototype.flat() is available in [node versions 11+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility).
- Pull Request merges into `nh-main`. Agent built from `master` will maintain dependency`.

NH-5414-Update-Dependencies-devDependencies-1

---

lib/probes/http.js
test/probes/http-trigger-trace.test.js

This pull request changes naming of headers and reported KV pairs for Trigger Trace requests.
`pd-keys` is now to `sw-keys` and it is reported as `SWKeys` rather than `PDKeys`.
- Pull Request merges into `nh-main` branch. Agent built from `master` will stay unchanged.

NH-5727-Trigger-Trace-Updates

---

test/probes/director.test.js

This pull request removes leftover deprecated `request` usage in the `director` test.

AO-16676-Replace-request-with-axios-2

---

lib/probes/tedious.js
package-lock.json
package.json
test/probes/tedious.test.js

This pull request updates `tedious` probe to work with recent versions of of the package.
* There was an api diversion at `11.0.10`. 
* Test pass for all "last majors": `11.8.0`, `12.3.0`, `13.2.0` and `14.0.0`
- Pull Request merges into `nh-main` branch. Agent built from `master` will stay unchanged.
- There is a need for MS SQL Server end-to-end integration test.

NH-7346-Add-Support-for-Tedious-Versions-11-12-13-14

---

lib/api.js
lib/probes/http.js
test/composite/axios.test.js
test/probes/http-common.js
test/probes/http-trigger-trace.test.js

This pull request updates the `http/s` probe(s) so that the key for the HTTP method kv is `HTTPMethod` as preferred by spec.
- Pull Request merges into `nh-main` branch. Agent built from `master` will stay unchanged.
- Minor cleanup alos piggy backing PR.

NH-7586-Change-Webserver-KV-to-HTTPMethod

---

lib/probe-defaults.js
lib/probes/mysql.js
lib/probes/oracledb.js
lib/probes/pg.js
lib/probes/tedious.js
lib/sql-trace-context.js
test/probes/mysql.test.js
test/probes/oracledb.test.js
test/probes/pg.test.js
test/probes/pg/subtests.js
test/probes/tedious.test.js
test/sql-trace-context.test.js

This pull request adds injection of Trace Context into database queries. The functionality is meant to allow integration with [SolarWinds DPM](https://docs.vividcortex.com/) using [Query Tags](https://docs.vividcortex.com/general-reference/query-tags/). Tags used are similar to those inserted by [sqlcommenter](https://github.com/open-telemetry/opentelemetry-sqlcommenter).
Changes are contained within the `mysql`, `pg`, `oracledb` and `tedious` probes without breaking any API barrier.
A new configuration value is introduced to each of the probes: `sqlTag`. It defaults to `false`.
For all probes tagging is done when the probe is *registered* and *enabled* and `sqlTag` is set to `true`, we are *tracing* and we are *sampling*.
Additionally, for the `pg` probe only, named prepared statement …

NH-5772-Trace-Context-in-Queries

---

lib/probe-defaults.js
lib/probes/dns.js
test/probes/dns.test.js
test/probes/mongoose.test.js
test/probes/pg.test.js
test/probes/tedious.test.js

This pull request adds auto instrumentation of Node's native [`DNS` module](https://nodejs.org/api/dns.html) to the agent.
A new probe named `dns` has been added. Instrumentation covers both the standard [callback api](https://nodejs.org/api/dns.html#dns) as well the [promise api](https://nodejs.org/api/dns.html#dns-promises-api).
Probe has basic configuration values that are set in a manner similar to all other probes.
```enabled: true```
```collectBacktraces: true```
The following KVs are reported.
`Spec` - string, required - **dns**
`Operation` - string, required - name of operation being performed.
`Args` - string, required - arguments passed to the operation.
`Flavor` - string, optional - the API used. Options are `callback` or `promise`. Not added for synchronous operations. …

NH-8430-Auto-Instrument-Node-DNS

---

lib/probes/fs.js
test/probes/fs.test.js

This pull request adds auto instrumentation to the [promise interface](https://nodejs.org/api/fs.html#promises-api) of Node's native [`fs` module](https://nodejs.org/api/fs.html).
Instrumentation covering the promise api was added to existing probe. 
A kv pair was added for async operations:
- `Flavor` - string, optional - the API used. Options are `callback` or `promise`. Not added for synchronous operations. 
[Spec](https://github.com/librato/trace/tree/master/docs/specs/KV) will be updated after this pull request is merged.
- The Promise API exposes a smaller set of methods when compared to the Callback and Sync APIs and thus instrumentation for promises is less extensive.
- When using Sync and Callback API's some operations generate sub spans. For example `appendFileSync` will result …

NH-8801-Auto-Instrument-Node-fs.promises-Interface

---

docs/api.md
lib/api-sim.js
lib/api.js
lib/probe-defaults.js
lib/probes/log4js.js
package.json
test/probes/log4js.test.js

This pull request adds auto instrumentation of the [`log4js`](https://www.npmjs.com/package/log4js) logging package to the agent.
A new probe named `log4js` has been added.
In log4js logging is done by calling a level function (e.g `logger.debug('say something')`) which then calls the `log` function, or alternatively, by directly calling the `log` function. Insertion is done by patching the lower level `log` function to cover all cases (including custom levels).
The implementation uses a "nested wrapper". It patches the `getLogger`  function so that when it is invoked, it will patch an internal `log` function of the returned logger object.
In order to provide granular control as what layouts are auto patched, and which is left for the user to configure, The implementation patches the …

NH-5459-Support-Trace-ID-Insertion-for-log4js

---

CONFIGURATION.md
docs/api.md
lib/api-sim.js
lib/api.js
lib/get-unified-config.js
lib/index.js
lib/probes/bunyan.js
lib/probes/log4js.js
lib/probes/morgan.js
lib/probes/pino.js
lib/probes/winston.js
package-lock.json
package.json
test/get-unified-config.test.js
test/no-addon/custom.test.js
test/probes/log4js.test.js
test/probes/morgan.test.js
test/probes/winston.test.js

This pull request refactors Logging API and the logging probes (`bunyan`, `log4js`, `morgan`, `pino`, `winston`) that use said API.
Method is used in the logging probes.
It augments a passed object with additional keys. This is an anti-pattern.
`getTraceObjecForLog` will allow user (or probe developer) to get the log object (essentially the trace object but also with a "zeroed" option) and then decide what to do with it (which is usually just plugging it into the log object).
It pairs with `getTraceStringForLog` (renamed from `getLogString` to match naming of sibling method) that is introduced for text log insertion in https://github.com/appoptics/appoptics-apm-node/pull/228 
Currently there are two config options: `insertTraceIdsIntoLogs` and `insertTraceIdsIntoMorgan`.
The need for the …

NH-9432-Refactor-Logging-Probes-API

---

CONFIGURATION.md
lib/get-unified-config.js
lib/index.js
lib/probes/morgan.js
test/get-unified-config.test.js
test/probes/morgan.test.js

This pull request refactors the `morgan` probe.
- Probe is implemented in a unique manner using a Proxy. It does not use the [shimmer third party package](https://www.npmjs.com/package/shimmer) used by all other probes. It’s a nice concept, but it “breaks the pattern”.
- Probe uses a probe specific config `createTraceIdsToken` that is conditionally nested under (now deprecated) `insertTraceIdsIntoMorgan`, a pattern none of the other probes use. The need for that specific setting is also unclear as creating a morgan token is part of the "normal flow" of instrumentation.
- Trace data insertion into predefined format is done with a token, but is then unnecessarily conditionally checked each time logging is invoked.
- Trace insertion into the predefined dev format (which is a compiled …

NH-9492-Refactor-Morgan-Probe

---

package-lock.json
package.json

This pull request upgrades `minimist` to version `1.2.6`
Previous versions of `minimist` had a prototype pollution bug that could cause privilege escalation in some circumstances when handling untrusted user input.
Please use version 1.2.6 or later:
https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795 (version <=1.2.5)
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764 (version <=1.2.3)
see: https://www.npmjs.com/package/minimist
- Since  `minimist` is a dependency, a patch release of agent is warranted.

AO-21090-minimist-Dependency-Upgrade

---

package.json

This pull request upgrades dependencies to latest where available and possible.
Updated:
- `semver` to `7.3.5`
- `methods` to `1.1.2`
- `glob` to `7.2.0`
- Since these are dependencies, a patch release of agent is warranted.
- `array-flatten` is “stuck” at `2.1.2`. Latest at `3.0.0` is breaking. Dependency removed for in `nh-main` branch.

AO-21093-Update-Dependencies-to-Latest

---

.github/workflows/verify.yml

This pull request fixes the Verify workflow modified in to #238. 
Workflow [works as expected](https://github.com/appoptics/appoptics-apm-node/actions/runs/2162361978) with fix.

AO-21104-Refactor-Tests-and-GH-Actions-for-Future-Proofing-fix

---

package.json
test.sh

The lambda implementation suffers form several issues (AO-19620, AO-19603, AO-19911, AO-20761) and thus serverless support would not initially ship for `solarwinds-apm`.
This pull request removes:
- The version suffix used by lambda from package.json. 
- The `appoptics-auto-lambda` dependency from package.json
- Skips lambda tests.
All other lambda related functionality, added in #124, #127, #131, #143 is left as-is.
- Pull Request merges into `nh-main` branch. Bindings built from `master` will stay unchanged.
- Functionality also gracefully disabled in bindings https://github.com/appoptics/appoptics-bindings-node/pull/109

NH-11224-Gracefully-Disable-Lambda-Functionality

---

package-lock.json
package.json

This pull request removes `minimist` from dependencies and moving it to devDependencies (where it is only used for utility by the, currently gracefully disabled, lambda implementation).
`minimist` was added as dependency in https://github.com/appoptics/appoptics-apm-node/commit/ce5890d2ab0e8be98b7ebae047c32f3c3de74e2f
Need for package was removed in #241
- Pull Request merges into `nh-main`. Agent built from `master` will maintain dependency`.

NH-5414-Update-Dependencies-devDependencies-3

---

lib/index.js
test.sh
test/no-service-key/custom.test.js

This pull request modifies the conditions under which the context store package is required in order to fix errors experienced by users.
- When the agent is disabled (for any number of reasons), auto instrumentation probes are *not* loaded. 
-  Custom instrumentation however may be written in such a way that it is called even when the agent is disabled. The agent thus provides an ["api simulator"](https://github.com/appoptics/appoptics-apm-node/blob/AO-21089-Patch/lib/api-sim.js) with a signature similar to that of the "real" api. That "api simulator" is [loaded instead of the "real" api](https://github.com/appoptics/appoptics-apm-node/blob/AO-21089-Patch/lib/index.js#L364) when the agent is initialized.
- To maintain context during async operations the agent relies on a 3rd party …

AO-21089-Patch

---

package-lock.json
package.json
test/probes/http-common.js

This pull request fixes the http probe tests so that they actually run as expected.
Since the tests did not run as expected, an issue with bindings/liboboe trace continuation when Downstream was not detected.
With the fixed tests, a test will fail when using bindings below version `12.0.0-nh.2` (comes with liboboe `10.5.0`).
See: https://github.com/appoptics/appoptics-apm-node/runs/6713249942?check_suite_focus=true
```
57 suites in 5 groups passed
2 suites in 1 group failed
PROBES:
test/probes/http.test.js
test/probes/https.test.js
```
All tests will pass once https://github.com/appoptics/appoptics-bindings-node/pull/118 is merged and the updated bindings are installed in the agent `nh-main` branch from the bindings `nh-main` branch. see: …

NH-14130-Fix-http-Tests

---

lib/addon-sim.js
lib/probes/cassandra-driver.js
lib/probes/mysql.js
lib/probes/node-cassandra-cql.js
lib/probes/oracledb.js
lib/probes/pg.js
lib/probes/tedious.js
lib/sql-sanitizer.js
package-lock.json
package.json
test/probes/cassandra-driver.test.js
test/probes/mysql.test.js
test/probes/oracledb.test.js
test/probes/pg/subtests.js
test/probes/tedious.test.js
test/sql-sanitizer.test.js

This pull request adds SQL Sanitization functionality to the agent.
SQL sanitazation (in this context) is the removal of user data from query strings (e.g. removing `Jake` and `13` from `SELECT * FROM users WHERE name = 'Jake' AND age > 13`).
Sanitization was added to the agent via the [bindings](https://github.com/appoptics/appoptics-bindings-node/commit/d82692bb8d57b106114dbac7f4efc878054fc214). It is an FSM written in C++ ["copied" from PHP agent](https://github.com/librato/oboe/blob/834a1afb4cfafa2c38e7b8f3bbcf35b528c35ab2/contrib/php_oboe/php-oboe/php-8/sql_parser.cc).
The Ruby Agent uses a [simple regex](https://github.com/appoptics/appoptics-apm-ruby/blob/3a96150e6991c0d61b8ca859d62ebb16c9fa587f/lib/rails/generators/solarwinds_apm/templates/solarwinds_apm_initializer.rb#L168) to …

NH-13411-Add-SQL-Sanitization-Code

---

package-lock.json
package.json
test/probes/http-websocket-common.js

This pull request "unskips" web socket tests that were skipped in https://github.com/appoptics/appoptics-apm-node/commit/7c3230da467dac81640a2f1a0889c10fec086a57 replacing the now dead websocket.org with websocket.events.
websocket.events is operated by Lob and they say ["You’re also welcome to use ours at echo.websocket.events."](https://www.lob.com/blog/websocket-org-is-down-here-is-an-alternative) - so we'll do for now.
- Pull Request merges into nh-main branch.

NH-14040-Replace-websocket.org-in-Tests

---

lib/index.js
package-lock.json
package.json
test/integrity.test.js
test/probes/fs.test.js

This pull request removes `cls-hooked` from dependencies.
The package is redundant. Context is managed with `ace-context`.
- `ace-context` is a fork of `cls-hooked`, `cls-hooked` is a fork of `continuation-local-storage`
- Managing context using [`continuation-local-storage`](https://www.npmjs.com/package/continuation-local-storage) was added in one of the early commits as part of a "quick-and-dirty port of trace and log functionality from oboe-ruby"  (See: https://github.com/appoptics/appoptics-apm-node/commit/1b5c028c00752dd86ac47c7aff8fbae79f58d467)
- `continuation-local-storage` was replaced with a fork called [`cls-hooked`](https://www.npmjs.com/package/cls-hooked) 4 years later in: https://github.com/appoptics/appoptics-apm-node/commit/4345f61d3fb30ff4cdd2e2e4f746ccf95cd6bb58
- A …

NH-5414-Update-Dependencies-devDependencies-5 (cls-hooked) 

---

test/probes/http-websocket-common.js

Reverts appoptics/appoptics-apm-node#266
Tests fail randomly too many times while running in GitHub Actions.

Revert "NH-14040-Replace-websocket.org-in-Tests"

---

lib/debug-custom.js
lib/loggers.js
package-lock.json
package.json
test/integrity.test.js

This pull request "unbundles" `debug-custom` package dependency into local module. That local module depends on the actively maintained `debug` package.
[`debug-custom`](https://www.npmjs.com/package/debug-custom) was introduced in https://github.com/appoptics/appoptics-apm-node/pull/54 replacing [`debug`](https://www.npmjs.com/package/debug)
It was made by former maintainer for use in the Agent. 
Readme says: 
> “... debug-custom is a thin wrapper around `debug` that allows the user to hide whatever prefix is used to prevent conflicts. debug-custom also makes it easier to add and remove debug levels dynamically under program control.” 
- As of June 17, 2022
- `debug` Last published 3 months ago ago, has 182,971,812 Weekly Downloads and 43,521 Dependents.
- `debug-custom` was Last …

NH-5414-Update-Dependencies-devDependencies-6 (debug-custom)

---

lib/log-formatters.js
lib/require-patch.js

This pull request resolves circular dependencies in agent code.
- `/log-formatters.js` was added in https://github.com/appoptics/appoptics-apm-node/commit/8b8e19b38fbeb28cd618edf0ad5f0e7dc7716b32 and https://github.com/appoptics/appoptics-apm-node/commit/e6cff9cb0a959235e2598361e313129cc00ced16 created a circular dependency (2018).
- Running [Madge](https://www.npmjs.com/package/madge):
```
Processed 58 files (1.3s) (1 warning)
✖ Found 2 circular dependencies!
1) index.js > loggers.js > log-formatters.js
2) index.js > require-patch.js
```
Node documentation says: 
> Careful planning is required to allow cyclic module dependencies to work correctly within an application. https://nodejs.org/api/modules.html#modules_cycles. 
However at this point we can assume this is not a cause of customer …

NH-13380-Resolve-Circular-Dependencies

---

lib/probes/q.js
test/probes/promises/index.js

This pull request fixes issues with the `q` probe so that it only binds when tracing (i.e. in the context of an http request).
- The probe generated excessive logging when used outside the context of an http request. It that was apparent in test runs and caused customer concern. 
- A fix similar to the one in the pull request was [implemented in the `bluebird` probe](https://github.com/appoptics/appoptics-apm-node/commit/4cbb3a60e36160dbd40e9324223134cc310294d1) a while back.
Probe was changed to only bind functions when tracing. Tests were cleaned.
- Pull Request merges into `nh-main`. Agent built from `master` will stay "unfixed"`.

NH-14027-Fix-q-Probe

---

lib/get-unified-config.js
test/get-unified-config.test.js

This pull request changes logging code so that it masks a service key output in the logged error even if the input value itself is not a valid service key.
When user is providing an invalid service key, application logs will contain what was provided as-is. An invalid service key may still expose a valid and usable token or part thereof.
Always mask the service key provided.
- Pull Request merges into `nh-main`. Agent built from `master` will stay unchanged.

NH-16920-Mask-Logged-Service-Key-when-Invalid

---

lib/probes/dns.js
test/probes/dns.test.js

This pull request fixed parsing of arguments for the Arg Key Value pair so that the arguments displays correctly when they include objects.
When arguments contain objects - the JSON representation of the object is displayed in the comma delimited representation of the args array.
- Pull Request merges into `nh-main`. Agent built from `master` will stay unchanged.

NH-8430-Auto-Instrument-Node-DNS (fix)

---

README.md

This pull request is a documentation change attempting to clarify without complxifiing.
Test is based on what was merged in https://github.com/solarwindscloud/solarwinds-apm-node/pull/15
Live editing on GitHub is welcomed.
In order to provide instrumentation, the instrumented app has to require the Node agent prior to all other modules.
In the past (AppOptics UI and all docs) users were instructed to add `require('appoptics-apm')` to the top of their entry point JS file.
As long as the instrumented app is “vanilla” JavaScript, those two methods are identical. However, as more and more users use a transpile & build process to create their Node apps, the require (or import) method no longer works since the bundler (a la webpack) is unable to work with the bindings binaries.
While there may …

Change-Agent-Config-Instructions-to-use-CLI-Require-as-Default
